### PR TITLE
fix(index): use universal runtime api

### LINKED ISSUE #102: No Universal Runtime Support
```bash
## Purge Flexy CSS
curl -X "HLXPURGE" "https://pages--adobe.hlx.live/styles/blocks/flexy.css?1"
```
```http
HTTP/1.1 404 Not Found
Connection: close
Content-Length: 91
Content-Type: text/plain; charset=utf-8
Apigw-Requestid: akt1JgtdIAMEMGA=
X-Backend-Health: 1 1
Accept-Ranges: bytes
X-Version: 517; src=517; cli=8.4.6; rev=online
Content-Security-Policy: frame-ancestors 'self'
Via: 1.1 varnish, 1.1 varnish
Cache-Control: max-age=7200
Date: Thu, 11 Feb 2021 09:19:03 GMT
X-Served-By: cache-bwi5121-BWI, cache-ams21025-AMS
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1613035143.165249,VS0,VE183
Vary: X-Debug,X-Strain,X-Request-Type,X-Forwarded-Host,X-OW-Version-Lock, Accept-Encoding
Strict-Transport-Security: max-age=31557600
Function not found: arn:aws:lambda:us-east-1:118435662149:function:helix-services--purge:v1
```

### PR DESCRIPTION
**Pull request by trieloff**
fixes #102

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

File: test/utils.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+      headers: new Map(Object.entries(params.__ow_headers || {})),
+    }, {
+      resolver,
+      env,
+      // eslint-disable-next-line no-underscore-dangle
+      log: params.__ow_logger,
+    });
+    return {
+      statusCode: resp.status,
+      body: JSON.parse(await resp.text()),
```
Comment (stefan-guggisberg) [inline test/utils.js:32]:
```suggestion
      body: await resp.json(),
```

**Review by stefan-guggisberg — APPROVED** [review]
I would also update the following dependencies:
```
    "@adobe/fastly-native-promises": "1.19.11",
    "@adobe/helix-fetch": "2.1.3",
    "@adobe/helix-status": "9.0.2",
```
